# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


userSeed = [
    {username: "user1", password: "abc123", name: "Wannabe", age: 15, gender: "male", bio: "A average young boy. Everything is average.", looks: 5, smarts: 5, athletic: 5, finance: 5, kindness: 5},
    {username: "user2", password: "abc123", name: "MagicalFlower", age: 15, gender: "female", bio: "A average young girl. Love everything that is cute.", looks: 5, smarts: 5, athletic: 5, finance: 5, kindness: 5}
]

User.create(userSeed)


outfitSeed = [
    {outfitname: "uniformNum1", headwear: "white baseball cap", topwear: "white polo tshirt", bottomwear: "white jogging pants", shoe: "white nike training shoe", accessories: "necklace whistle", user_id: 1},
    {outfitname: "uniformNum2", headwear: "none", topwear: "blackcoat", bottomwear: "black pants", shoe: "shiny black shoe", accessories: "gold necklace", user_id: 1},
    {outfitname: "uniformNum3", headwear: "catear", topwear: "cat printed shirt", bottomwear: "paw printed pants", shoe: "cat paw show", accessories: "cat glasses", user_id: 2},
  
]

Outfit.create(outfitSeed)

characterSeed = [
    {name: "Lucy Heartfilia", age: 18, gender: "female", occupation: "Celestial Spirit Wizard", lovePoint: 50, favorite: false, bio: "Lucy is an independent novice mage searching for a mage guild to join, particularly interested in Fairy Tail, which she claims as the strongest mage guild.", imageURL: "https://res.cloudinary.com/dfqzcsl8x/image/upload/v1602968344/Project4/Lucy_Heartfilia_jzvluw.jpg"},
    {name: "Asuna Yuuki", age: 15, gender: "female", occupation: "Gamer", lovePoint: 50, favorite: false, bio: "Asuna is a friend of Kirito and is a sub-leader of the guild Knights of the Blood (KoB), a medium-sized guild of about thirty players, also called the strongest guild in Aincrad.", imageURL: "https://res.cloudinary.com/dfqzcsl8x/image/upload/v1602968343/Project4/Asuna_Yuuki_cisvps.jpg"},
    {name: "Naruto Uzumaki", age: 19, gender: "male", occupation: "Ninja", lovePoint: 50, favorite: false, bio: "Born in Konohagakure, a ninja village hidden in the leaves, Naruto Uzumaki was destined for greatness. Vowing to become Hokage one day and using his will to never give in.", imageURL: "https://res.cloudinary.com/dfqzcsl8x/image/upload/v1602968345/Project4/Naruto_Uzumaki_ormvxe.jpg"},
    {name: "Rem", age: 17, gender: "female", occupation: "Maid", lovePoint: 50, favorite: false, bio: "Rem is one of the twin maids working for Roswaal L Mathers. She tends to speak in a superficially polite manner and sometimes acts without thinking. She holds both worshipping respect and guilt toward her sister for an incident in the past; because of this, Rem tends to think of herself as inferior.", imageURL: "https://res.cloudinary.com/dfqzcsl8x/image/upload/v1602968346/Project4/Rem_t5imon.jpg"},
    {name: "Umaru Doma", age: 16, gender: "female", occupation: "Student", lovePoint: 50, favorite: false, bio: "Umaru is the perfect high school girl who is regarded for her looks, personality, grades, and just about everything; however, when she is at home with her older brother, she dons a hood and acts as a lazy shut-in who loves playing video games, eating junk food, looking at manga/anime, and buying stuff online.", imageURL: "https://res.cloudinary.com/dfqzcsl8x/image/upload/v1602968347/Project4/Umaru_Doma_jktg1r.jpg"},
    {name: "Kakashi Hatake", age: 31, gender: "male", occupation: "Ninja", lovePoint: 50, favorite: false, bio: "Kakashi's Sharingan eye gives him a significant advantage in battle, as he can copy enemy techniques and use them as his own, as well as track and predict his opponent's movements flawlessly.", imageURL: "https://res.cloudinary.com/dfqzcsl8x/image/upload/v1602968344/Project4/Kakashi_Hatake_wagkq8.jpg"},
    {name: "Kazuto Kirigaya", age: 15, gender: "male", occupation: "Gamer", lovePoint: 50, favorite: false, bio: "He is a solo player, a player who hasn't joined a guild and usually works alone. He is also one of the very few people to have had the privilege to play in the beta testing period of Sword Art Online.", imageURL: "https://res.cloudinary.com/dfqzcsl8x/image/upload/v1602968345/Project4/Kazuto_Kirigaya_vcj0af.jpg"},
    {name: "Rin Toosaka", age: 15, gender: "female", occupation: "Mage", lovePoint: 50, favorite: false, bio: "Rin is a model student and idol of Shirou's school. She is secretly a Magus and a Master in the Fifth Holy Grail War.", imageURL: "https://res.cloudinary.com/dfqzcsl8x/image/upload/v1602968345/Project4/Rin_Toosaka_rdw6pp.jpg"},
    {name: "Haruhi Suzumiya", age: 16, gender: "female", occupation: "Student", lovePoint: 50, favorite: false, bio: "She is introduced declaring her interests in aliens, espers and time travelers and does not care for ordinary human beings. The last thing on her mind is a normal high school life.", imageURL: "https://res.cloudinary.com/dfqzcsl8x/image/upload/v1602968344/Project4/Haruhi_Suzumiya_enaxrd.jpg"},
    {name: "Gon Freecss", age: 12, gender: "male", occupation: "Hunter", lovePoint: 50, favorite: false, bio: "Gon's an innocent boy who is willing to help anyone, especially his friends. He rarely ever looks at anything in a bad way. His curious and naive personality often frustrates his friends but this is also the reason why many people are attracted to him. He is also from the enhancer nen group. He usually fights barehanded or with his fishing rod, but it is seen quite often that Gon's fist is more deadly than any weapons.", imageURL: "https://res.cloudinary.com/dfqzcsl8x/image/upload/v1602968345/Project4/Gon_Freecss_boaycd.jpg"},
    {name: "Shouto Todoroki", age: 15, gender: "male", occupation: "Hero", lovePoint: 50, favorite: false, bio: "Shouto has bi-colored hair, the right side is white, the left one is red. He has a burn on his left eye. In his Hero Costume, Shouto wears a dark blue jacket, dark blue pants, a silver-colored combat vest, and white boots. He also wears a silver-colored belt with metal capsules.", imageURL: "https://res.cloudinary.com/dfqzcsl8x/image/upload/v1602968346/Project4/Shouto_Todoroki_aduyey.jpg"},
    {name: "Gintoki Sakata", age: 28, gender: "male", occupation: "Samurai", lovePoint: 50, favorite: false, bio: "Gintoki has naturally permed silver hair, which he blames for his lacking love-life. He has a big crush on the TV's news weather girl, Ketsuno. He is obsessed with sweet food such as parfaits, ice cream and cakes. His second obsession is reading the manga anthology magazine Weekly Shounen Jump.", imageURL: "https://res.cloudinary.com/dfqzcsl8x/image/upload/v1602968344/Project4/Gintoki_Sakata_gadotj.jpg"},
    {name: "Megumin", age: 13, gender: "female", occupation: "Arch Wizard", lovePoint: 50, favorite: false, bio: "An arch wizard who is descended from crimson demons; powerful humanoids who possess black hair and red eyes, and sport chuunibyou characteristics. Megumin only knows a single skill, the incredibly powerful explosion magic that immediately incapacitates her for the rest of the day when cast, and refuses to learn any other skills.", imageURL: "https://res.cloudinary.com/dfqzcsl8x/image/upload/v1602968345/Project4/Megumin_es77nf.jpg"},
    {name: "Emilia", age: 18, gender: "female", occupation: "Witch", lovePoint: 50, favorite: false, bio: "Emilia is good natured and likes to take care of others, though she herself refuses to admit it, instead thinking of it as her own selfishness. She is indifferent to her own appearance, leaving Puck to take care of her clothes and hair.", imageURL: "https://res.cloudinary.com/dfqzcsl8x/image/upload/v1602968343/Project4/Emilia_ehqzal.jpg"},
    {name: "Natsu Dragneel ", age: 18, gender: "male", occupation: "Fire Wizard", lovePoint: 50, favorite: false, bio: "Natsu has a carefree and reckless nature and, despite his constant brawls with the other members of the guild, is a fiercely loyal and protective friend. He has a particularly close, and competitive relationship with fellow members; Gray Fullbuster and Erza Scarlet.", imageURL: "https://res.cloudinary.com/dfqzcsl8x/image/upload/v1602968345/Project4/Natsu_Dragneel_drviwm.jpg"},
    {name: "Yui Hirasawa", age: 16, gender: "female", occupation: "Musician", lovePoint: 50, favorite: false, bio: "Yui is a girl who's easily distracted by cute things and tasty food. She's a crybaby but cheers up easily if she gets some sweets. She eats a lot of sweets but she does not gain as much as she eats.", imageURL: "https://res.cloudinary.com/dfqzcsl8x/image/upload/v1602968347/Project4/Yui_Hirasawa_sxslu1.jpg"},
    {name: "Tanjirou Kamado", age: 13, gender: "male", occupation: "Demon Slayer", lovePoint: 50, favorite: false, bio: "A Demon Hunter and joins the Demon Killing Corps to hunt down the demon who murdered his family and turned his sister Nezuko into a demon.", imageURL: "https://res.cloudinary.com/dfqzcsl8x/image/upload/v1602968346/Project4/Tanjirou_Kamado_wn1jt3.jpg"},
    {name: "Tetsuya Kuroko", age: 16, gender: "male", occupation: "Basketball Player", lovePoint: 50, favorite: false, bio: "At the first glance all of his abilities seem to be below average, but despite being bad at dribbling and shooting he can be a dangerous opponent. He specializes in circulating passes without being seen.", imageURL: "https://res.cloudinary.com/dfqzcsl8x/image/upload/v1602968347/Project4/Tetsuya_Kuroko_zkyvhd.jpg"},
    {name: "Akame", age: 16, gender: "female", occupation: "Night Raid Assassin", lovePoint: 50, favorite: false, bio: "Akame is often considered to be one of the stronger members of Night Raid, slaying even the strongest of enemies with minimal effort. Her hellish assassination training allows her combat ability to be on par with those as powerful as General within the military levels of the Empire. Her Teigu, One Cut Killer: Murasame, is a katana known for being coated in an immensely deadly poison that can kill those cut by it within seconds.", imageURL: "https://res.cloudinary.com/dfqzcsl8x/image/upload/v1602968343/Project4/Akame_mb8f4e.jpg"},
    {name: "Kagura", age: 14, gender: "female", occupation: "Alien Hunter", lovePoint: 50, favorite: false, bio: "She is super-strong and can stop a speeding motor-scooter with one hand. Although stronger than most humans, she cannot control her strength perfectly. Her super-human strength makes her extremely bad with pets.", imageURL: "https://res.cloudinary.com/dfqzcsl8x/image/upload/v1602968345/Project4/Kagura_vwwgmz.jpg"},
    {name: "Shana", age: 12, gender: "female", occupation: "Mage", lovePoint: 50, favorite: false, bio: "Shana is a young girl with jet black hair which is almost as long as her entire body height. She also has dark brown pupils and a fair complexion. Because of the effects of being a Flame Haze, Shana's body age remains to that of a girl of 11 to 12 years old.", imageURL: "https://res.cloudinary.com/dfqzcsl8x/image/upload/v1602968346/Project4/Shana_dmjbln.jpg"},
    {name: "Erina Nakiri", age: 16, gender: "female", occupation: "Chef", lovePoint: 50, favorite: false, bio: "Born in the prestige and influential family with affluent finances and refined pedigree, Erina is one of the arrogant, prideful and pampered students in Tootsuki Culinary Academy. Having a reputation known as God's Tongue for an ability to taste the food accurately and excel cooking skills.", imageURL: "https://res.cloudinary.com/dfqzcsl8x/image/upload/v1602968343/Project4/Erina_Nakiri_dqijfx.jpg"},
    {name: "Bell Cranel", age: 15, gender: "male", occupation: "Adventurer", lovePoint: 50, favorite: false, bio: "He wears light armor and usually carries around a small blade. He is a kind yet shy boy and is easily intimidated when facing a stronger opponent. He cares deeply for the people around him especially his goddess Hestia.", imageURL: "https://res.cloudinary.com/dfqzcsl8x/image/upload/v1602968343/Project4/Bell_Cranel_bhgber.jpg"},
    {name: "Kirino Kousaka", age: 15, gender: "female", occupation: "Student/Model", lovePoint: 50, favorite: false, bio: "She is mature for her age with a cold, tsundere-like personality. She has a strong little sister fetish and owns many adult games with older brother/little sister themes, relying on a modeling job to pay for them.", imageURL: "https://res.cloudinary.com/dfqzcsl8x/image/upload/v1602968343/Project4/Kirino_Kousaka_kix3oo.jpg"},
    {name: "Kaito Kuroba", age: 17, gender: "male", occupation: "Thief", lovePoint: 50, favorite: false, bio: "The Phantom Thief Kid or The Magician Under the Moonlight (Kaito Kid) is a world-renowned thief who steals treasures and gems. He is sometimes known as Kaito Kid or International Criminal 1412.", imageURL: "https://res.cloudinary.com/dfqzcsl8x/image/upload/v1602968345/Project4/Kaito_Kuroba_dc1kze.jpg"},
    {name: "Sagiri Izumi", age: 10, gender: "female", occupation: "Illustrator", lovePoint: 50, favorite: false, bio: "Sagiri became interested in live video feeds and started drawing images on a camera disguising her face and voice so that nobody would recognize her or learn about her.", imageURL: "https://res.cloudinary.com/dfqzcsl8x/image/upload/v1602968346/Project4/Sagiri_Izumi_icaenq.jpg"},
    {name: "Lala Deviluke", age: 16, gender: "female", occupation: "Alien Princess", lovePoint: 50, favorite: false, bio: "Lala has far more strength, power and speed than the average human. She can fire laser beams from her tail. However, her tail is both her weapon and her weakness.", imageURL: "https://res.cloudinary.com/dfqzcsl8x/image/upload/v1602968344/Project4/Lala_Deviluke_zdz8y5.jpg"},
    {name: "Sanji", age: 21, gender: "male", occupation: "Cook", lovePoint: 50, favorite: false, bio: "Sanji uses an array of powerful and varied kicking moves when he fights. His cooking skills are world class, and he was mentored in both cooking and fighting by Chef Red Leg Zeff of the Baratie. He was born in the North Blue, but grew up in the East Blue.", imageURL: "https://res.cloudinary.com/dfqzcsl8x/image/upload/v1602968346/Project4/Sanji_i6aj2s.jpg"},
]


Character.create(characterSeed)

appointmentSeed = [
    {date: Date.parse("2020-10-17"), location: "Starbucks", user_id: 1, outfit_id: 1, character_id: 1},
    {date: Date.parse("2020-10-19"), location: "Lowes", user_id: 1, outfit_id: 2, character_id: 1},
    {date: Date.parse("2020-10-21"), location: "Sea World", user_id: 2, outfit_id: 1, character_id: 1}
]

Appointment.create(appointmentSeed)